#!/bin/sh
BUILDINFO_HEADER=$1

function generate_header
{
    (
        TALON_SHA1_HASH=`git rev-parse --short HEAD`
        TALON_REVISION_DATE=`git log -1 --pretty=%ai`
        CURRENT_DATE=`date`
        CURRENT_BRANCH=`git branch 2> /dev/null | tr -d \*\ `
        TALON_LAST_RELEASE=`git describe --tags --always`
        
        echo "- Generating $BUILDINFO_HEADER for SHA1 $TALON_SHA1_HASH."
        
        if ([ -e "$BUILDINFO_HEADER" ]) then
            echo "- Removing previous header at $BUILDINFO_HEADER"
            rm -f "$BUILDINFO_HEADER"
        fi
        
        echo "// This file was generated by a tool. Do not modify this file.
        
#pragma once

#define TALON_VERSION_BUILD \"$TALON_SHA1_HASH\"

#define TALON_VERSION_BRANCH \"$CURRENT_BRANCH\"
#define TALON_VERSION_REVISION_DATE \"`date -d "$TALON_REVISION_DATE"`\"
#define TALON_VERSION_CURRENT_DATE \"`date -d "$CURRENT_DATE"`\"
#define TALON_VERSION_REVISION_DATE_VERBOSE \"`date -d "$TALON_REVISION_DATE" "+%A, %B %d, %Y at %r"`\"
#define TALON_VERSION_CURRENT_DATE_VERBOSE \"`date -d "$CURRENT_DATE" "+%A, %B %d, %Y at %r"`\"

#define TALON_RELEASE_NAME \"$TALON_LAST_RELEASE\"

" > "$BUILDINFO_HEADER"
        
        exit 0
    )
}

# -d filename
if [ x$BUILDINFO_HEADER = x ]; then
    echo "* You must specify the path of the buildinfo header file."
    exit 1
fi

generate_header;