// This file was generated by a tool. Do not modify this file.
        
#pragma once

#define TALON_VERSION_BUILD "4cff919"

#define TALON_VERSION_BRANCH "master"
#define TALON_VERSION_REVISION_DATE "Tue Apr 10 22:13:16 PDT 2012"
#define TALON_VERSION_CURRENT_DATE "Wed Apr 11 13:42:31 PDT 2012"
#define TALON_VERSION_REVISION_DATE_VERBOSE "Tuesday, April 10, 2012 at 10:13:16 PM"
#define TALON_VERSION_CURRENT_DATE_VERBOSE "Wednesday, April 11, 2012 at 01:42:31 PM"

#define TALON_RELEASE_NAME "4cff919"


