
#pragma once

#define TALON_STABLE_BUILD 0

#define TALON_VERSION_MAJOR 0
#define TALON_VERSION_MINOR 1
#define TALON_VERSION_PATCH 0
#define TALON_VERSION_SUFFIX "Alpha"
#define TALON_VERSION_NAME "Awesome"

#define TALON_VERSION    ((TALON_VERSION_MAJOR << 16) | (TALON_VERSION_MINOR << 8) | TALON_VERSION_PATCH)

#include <Talon/TalonBuildInfo.h>

#define TALON_STR(x) #x
#define TALON_WSTR(x) L#x
#define TALON_PASTE(x) x
#define TALON_WPASTE(x) L##x
#define TALON_TOSTRING(x) TALON_STR(x) 
#define TALON_TOWSTRING(x) TALON_WSTR(x)
#define TALON_TOPASTE(x) TALON_PASTE(x) 
#define TALON_TOWPASTE(x) TALON_WPASTE(x)

#if TALON_STABLE_BUILD
#	define TALON_MAKE_VERSION_STRING(a, b, c, d) TALON_TOSTRING(a) "." TALON_TOSTRING(b) "." TALON_TOSTRING(c)
#	define TALON_MAKE_VERSION_WSTRING(a, b, c, d) TALON_TOWSTRING(a) L"." TALON_TOWSTRING(b) L"." TALON_TOWSTRING(c)
#else
#	define TALON_MAKE_VERSION_STRING(a, b, c, d) TALON_TOSTRING(a) "." TALON_TOSTRING(b) "." TALON_TOSTRING(c) " (Build " TALON_TOPASTE(d) ")"
#	define TALON_MAKE_VERSION_WSTRING(a, b, c, d) TALON_TOWSTRING(a) L"." TALON_TOWSTRING(b) L"." TALON_TOWSTRING(c) L" (Build " TALON_TOWPASTE(d) L")"
#endif
#define TALON_VERSION_STRING TALON_MAKE_VERSION_STRING(TALON_VERSION_MAJOR, TALON_VERSION_MINOR, TALON_VERSION_PATCH, TALON_VERSION_BUILD)
#define TALON_VERSION_WSTRING TALON_MAKE_VERSION_WSTRING(TALON_VERSION_MAJOR, TALON_VERSION_MINOR, TALON_VERSION_PATCH, TALON_VERSION_BUILD)